name: Deplay ASP.NET app to Azure Web App
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
env: {}
jobs:
  WebApplication220200611233303-build-and-deploy:
    env:
      AzureServiceName: WebApplication220200611233303
      DotNetVersion: 3.1.101
      LastUsedBuildConfiguration: Release
      ProjectGuid: 1861cf3b-fc00-41f7-a79c-eff21a9d32ba
      ResourceId: /subscriptions/07268dd7-4c50-434b-b1ff-67b8164edb41/resourceGroups/aapt0612Grop/providers/Microsoft.Web/sites/WebApplication220200611233303
      ResourceGroup: aapt0612Grop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: dotnet build and publish
      run: >-
        dotnet build --configuration Release --output dist\WebApplication220200611233303

        dotnet publish --configuration Release --output dist\WebApplication220200611233303
    - name: Deploy web app to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: WebApplication220200611233303
        publish-profile: ${{ secrets.WEBAPPLICATION220200611233303_PUBLISH_PROFILE }}
        package: dist\WebApplication220200611233303
