name: Deploy ASP.NET Core Web Application to avcPortalWebAppProd
on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: avcPortalWebAppProd
  AZURE_WEBAPP_PACKAGE_PATH: dist
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AVCPORTALWEBAPPPROD_PUBLISH_PROFILE }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  WORKFLOW_TYPE: azureAppServiceWindows
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@master
    - name: Setup .NET Core SDK ${{ env.DOTNET_CORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Run dotnet build and publish
      run: >
        dotnet build --configuration ${{ env.CONFIGURATION }}

        dotnet publish --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output"
    - name: Run Azure Web App Action
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output
