# CONFIGURATION
#  GitHub Action workflow template to deploy an ASP .NET Core app to Azure Web App Service (Windows)
name: Deploy ASP.NET Core app to Web App
on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: avcPortalWebAppProd
  AZURE_WEBAPP_PACKAGE_PATH: dist
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AVCPORTALWEBAPPPROD_PUBLISH_PROFILE }} 
  CONFIGURATION: Release
  DOTNET_VERSION: 3.1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub Action
        uses: actions/checkout@master
      
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Run dotnet build and publish
        run: |
          dotnet build --configuration ${{ env.CONFIGURATION }}
          dotnet publish --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output"
          
      - name: Run Azure Web App Action
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/output"
