name: Deplay ASP.NET app to Azure Web App
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
env: {}
jobs:
  avcPortalWebAppTest-build-and-deploy:
    env:
      AzureServiceName: avcPortalWebAppTest
      DotNetVersion: 3.1.101
      LastUsedBuildConfiguration: Release
      ProjectGuid: 1861cf3b-fc00-41f7-a79c-eff21a9d32ba
      ResourceId: /subscriptions/07268dd7-4c50-434b-b1ff-67b8164edb41/resourceGroups/avcPortalGrpWin/providers/Microsoft.Web/sites/avcPortalWebAppTest
      ResourceGroup: avcPortalGrpWin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: dotnet build and publish
      run: >-
        dotnet build --configuration Release --output dist

        dotnet publish --configuration Release --output dist
    - name: Deploy web app to Azure
      uses: azure/functions-action@v1
      with:
        app_name: avcPortalWebAppTest
        publish_profile: ${{ secrets.AVCPORTALWEBAPPTEST_PUBLISH_PROFILE }}
        package: dist
