name: Build and deploy .NET Core app to Windows WebApp WebApplication220201130003120
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: WebApplication220201130003120
  AZURE_WEBAPP_PACKAGE_PATH: src\WebAppPublishOnGit/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET_3f49}}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  WORKING_DIRECTORY: src\WebAppPublishOnGit
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.DOTNET_CORE_VERSION}}
    - name: Install dependencies
      run: dotnet restore ${{env.WORKING_DIRECTORY}}
    - name: Build
      run: dotnet build ${{env.WORKING_DIRECTORY}} --configuration ${{env.CONFIGURATION}} --no-restore
    - name: Publish artifact
      run: dotnet publish ${{env.WORKING_DIRECTORY}} --configuration ${{env.CONFIGURATION}} --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        publish-profile: ${{env.AZURE_WEBAPP_PUBLISH_PROFILE}}